no more more #defines in var all in goat

diff --git a/.github/workflows/trigger_tests.yml b/.github/workflows/trigger_tests.yml
--- a/.github/workflows/trigger_tests.yml
+++ b/.github/workflows/trigger_tests.yml
@@ -14,51 +14,50 @@ on:
 
 
 jobs:
-  trigger:
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Trigger tests repository
-        id: trigger
-        uses: peter-evans/repository-dispatch@v1
-        with:
-          token: ${{ secrets.REPO_ACCESS_TOKEN }}
-          repository: EPFLRocketTeam/C_AV_SIL
-          event-type: run-tests
-          client-payload: |
-            {
-              "branch": "${{ github.head_ref }}",
-              "baseref" : "${{github.base_ref}}",
-              "commit": "${{ github.sha }}",
-              "repo": "${{ github.repository }}",
-              "key": "${{github.event.pull_request.number}}"
-            }
-  checking:
-    runs-on: ubuntu-latest
-    needs: trigger
-    steps:
-      - name: Wait for workflow to complete
-        run: |
-          sleep 80
-          while true; do
-            sleep 10
-            STATUS=$(curl -s -H "Authorization: token ${{ secrets.REPO_ACCESS_TOKEN }}" \
-              "https://api.github.com/repos/EPFLRocketTeam/C_AV_SIL/actions/runs?event=repository_dispatch&status=completed" | \
-              jq -r '.workflow_runs[0].conclusion')
-            echo "Status: $STATUS"
-            if [ "$STATUS" == "success" ]; then
-              echo "Dispatched workflow succeeded"
-              break
-            elif [ "$STATUS" == "failure" ]; then
-              echo "Dispatched workflow failed"
-              exit 1
-            fi
-          done
+##  trigger:
+##    runs-on: ubuntu-latest
+##
+##    steps:
+##      - name: Trigger tests repository
+##        id: trigger
+##        uses: peter-evans/repository-dispatch@v1
+##        with:
+##          token: ${{ secrets.REPO_ACCESS_TOKEN }}
+##          repository: EPFLRocketTeam/C_AV_SIL
+##          event-type: run-tests
+##          client-payload: |
+##            {
+##              "branch": "${{ github.head_ref }}",
+##              "baseref" : "${{github.base_ref}}",
+##              "commit": "${{ github.sha }}",
+##              "repo": "${{ github.repository }}",
+##              "key": "${{github.event.pull_request.number}}"
+##            }
+##  checking:
+##    runs-on: ubuntu-latest
+##    needs: trigger
+##    steps:
+##      - name: Wait for workflow to complete
+##        run: |
+##          sleep 80
+##          while true; do
+##            sleep 10
+##            STATUS=$(curl -s -H "Authorization: token ${{ secrets.REPO_ACCESS_TOKEN }}" \
+##              "https://api.github.com/repos/EPFLRocketTeam/C_AV_SIL/actions/runs?event=repository_dispatch&status=completed" | \
+##              jq -r '.workflow_runs[0].conclusion')
+##            echo "Status: $STATUS"
+##            if [ "$STATUS" == "success" ]; then
+##              echo "Dispatched workflow succeeded"
+##              break
+##            elif [ "$STATUS" == "failure" ]; then
+##              echo "Dispatched workflow failed"
+##              exit 1
+##            fi
+##          done
           
 
   unit_tests:
     runs-on: ubuntu-latest
-    needs: trigger
     steps:
       - name: compile and test on remote device
         uses: appleboy/ssh-action@v1.0.3
